{
 "title": "Weather Station",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Forecast Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"forecasttemperature\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Forecast Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"forecasthumidity\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Current Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Forecast Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"forecastpressure\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Current Altitude",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._field == \"altitude\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Forecast Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._field == \"forecasttemperature\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Forecast Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._field == \"forecasthumidity\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Forecast Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"weather-station\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._field == \"forecastpressure\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  }
 ]
}